import HomeHeader from "./components/Header";
import "./globals.css";
import { Inter } from "next/font/google";

// Set up the font
const inter = Inter({
  subsets: ["latin"], // Required
});

export const metadata = {
  title: "Limm Local",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <HomeHeader />
        {children}
      </body>
    </html>
  );
}
