import Header from "./components/Header";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import { Inter } from "next/font/google";
import { LanguageProvider } from "./components/LanguageContext";
import { DeviceSizeProvider } from "./components/DeviceSizeContext";
import { cookies } from "next/headers";

// Set up the font
const inter = Inter({
  subsets: ["latin"], // Required
});

export const metadata = {
  title: "Limm Local",
  description: "Generated by Next.js",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const language = cookieStore.get("language")?.value || "en"; // Default to 'en'

  return (
    <html lang="en" className={inter.className}>
      <body>
        <DeviceSizeProvider>
          <LanguageProvider defaultLanguage={language}>
            <Header />
            {children}
          </LanguageProvider>
        </DeviceSizeProvider>
      </body>
    </html>
  );
}
