import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="shadow-md h-12 flex justify-center items-center text-xl font-bold text-black bg-red-200 text-center">Header</div>
        {children}
        <div className="shadow-md h-12 flex justify-center items-center text-xl font-bold text-black bg-blue-200 text-center fixed bottom-0 w-full">Footer</div>
      </body>
    </html>
  );
}
