import "./globals.css";
import Header from "./components/Header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="pt-14">
        {children}
        </div>
      </body>
    </html>
  );
}
